services:
  - type: web
    name: pocket-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8330981377:AAH3GUheRzKgpd4NDx0cIIGo4FVs1PDMyTA
      - key: TELEGRAM_CHAT_ID
        value: 1014815784